### ISSUE TITLE
GCAM not found

### ISSUE THREAD

**Issue by rubcalvo** [JGCRI/pygcam#27]
Hi! I've been traying to install and initialize pygcam several times, but i've encountered some problems. First of all, does pygcam can use GCAM Mac Release or GCAM has to be compiled manually? 
If pygcam can use GCAM MAC Release, when I try to initialize pygcam (git init) with GCAM 5.3 the following error appears:

INFO pygcam.gcam: GCAM not found at /Users/rcalvo/Desktop/gcam-v5.3-Mac-Release-Package/exe/Release; extracting version from path
gt failed: Failed to extract version number from path /Users/rcalvo/Desktop/gcam-v5.3-Mac-Release-Package/exe/Release

I have tried with different locations (gcam-v5.3-Mac-Release-Package, gcam-v5.3-Mac-Release-Package/exe, and so on).

Would much appreciate the help!

**Comment by rubcalvo** [comment]
Solved. It seems that the file directory is hardcoded in pygcam. 
Solved this issue by copying the gcam-v5.3-Mac-Release-Package folder to /Users/rcalvo/GCAM and rename it to gcam-v5.3

Altought I have encountered other issues after that. This issue is solved.

**Comment by rjplevin** [comment]
@rubcalvo , please email me at rich@plevin.com to resolve issues with pygcam.

I had neglected to update the init subcommand for the last 2 versions of GCAM (I'm working with a custom version, so it slipped my mind). I've updated it just now to recognize v5.3 and v5.4. The path to the GCAM installation is not hardcoded: it can be specified on the command-line, otherwise pygcam looks in several directories:

`dirs = [home, home + '/GCAM', home + '/gcam', home + '/Documents/GCAM', home + '/Documents/gcam']`
